'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
type Money={amount:number;currency:string}; type Account={id:string;institution:string;name:string;purpose:string;availableBalance:Money}; type Goal={id:string;name:string;targetAmount:Money;currentAmount:Money}; type Obligation={id:string;name:string;amount:Money;dueDate:string;status:string}; type Debt={id:string;name:string;outstandingAmount:Money;annualEffectiveRate:number;status:string}; type Action={id:string;type:string;amount:Money;rationale:string;status:string}; type Plan={totalConsolidatedBalance:Money;freeRealBalance:Money;dailySpendingLimit:Money;emergencyReserveBalance:Money;emergencyReserveTarget:Money;committedObligations:Money;nextIncomeDate:string;actions:Action[];warnings:string[]}; type Transaction={id:string;description:string;merchant?:string;type:string;amount:Money;category:string;occurredAt:string};
const labels:Record<string,string>={OPERATING:'Operação',EMERGENCY_RESERVE:'Reserva',GOAL:'Meta',INVESTMENT:'Investimento',PROPOSED:'Pendente',APPROVED:'Aprovada',REJECTED:'Recusada',RESERVE_FOR_OBLIGATIONS:'Reservar para compromissos',REDUCE_VARIABLE_SPENDING:'Reduzir gastos variáveis',PAY_HIGH_COST_DEBT:'Quitar dívida cara',TRANSFER_TO_EMERGENCY_RESERVE:'Reforçar reserva',CREATE_INVESTMENT_CONTRIBUTION:'Realizar aporte'};
const money=(v?:Money)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:v?.currency||'BRL'}).format(Number(v?.amount||0));
const date=(v?:string)=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(v)):'—';
const pretty=(v='')=>labels[v]||v.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
export default function Home(){
 const[config,setConfig]=useState({url:'http://localhost:8080',key:''}); const[showConfig,setShowConfig]=useState(false); const[loading,setLoading]=useState(false); const[msg,setMsg]=useState('Configure a chave da API para sincronizar seus dados.'); const[accounts,setAccounts]=useState<Account[]>([]); const[goals,setGoals]=useState<Goal[]>([]); const[obligations,setObligations]=useState<Obligation[]>([]); const[debts,setDebts]=useState<Debt[]>([]); const[transactions,setTransactions]=useState<Transaction[]>([]); const[plan,setPlan]=useState<Plan|null>(null);
 useEffect(()=>{const saved=localStorage.getItem('finflow-config');if(saved)queueMicrotask(()=>setConfig(JSON.parse(saved)))},[]);
 const api=useCallback(async<T,>(path:string,init?:RequestInit):Promise<T>=>{const headers=new Headers(init?.headers);headers.set('Accept','application/json');headers.set('X-API-Key',config.key);headers.set('X-FinFlow-Upstream',config.url.replace(/\/$/,''));if(init?.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');try{const r=await fetch(`/api/finflow${path}`,{...init,headers,cache:'no-store'});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.detail||p?.title||`Erro ${r.status}`);return p as T}catch(e){if(e instanceof TypeError)throw new Error('Não foi possível conectar à API FinFlow. Verifique se ela está em execução e se a URL está correta.');throw e}},[config]);
 const sync=useCallback(async()=>{if(!config.key){setShowConfig(true);return}setLoading(true);setMsg('Sincronizando visão financeira…');const now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1).toISOString();const rs=await Promise.allSettled([api<Account[]>('/api/v1/accounts'),api<Goal[]>('/api/v1/goals'),api<Obligation[]>('/api/v1/obligations'),api<Debt[]>('/api/v1/debts'),api<Plan>('/api/v1/plans/latest'),api<Transaction[]>(`/api/v1/transactions?from=${encodeURIComponent(from)}&to=${encodeURIComponent(now.toISOString())}`)]);const setters=[setAccounts,setGoals,setObligations,setDebts,setPlan,setTransactions] as Array<(v:never)=>void>;rs.forEach((r,i)=>{if(r.status==='fulfilled')setters[i](r.value as never)});const failed=rs.filter(r=>r.status==='rejected');setMsg(failed.length===rs.length?(failed[0]as PromiseRejectedResult).reason.message:failed.length?`Sincronizado com ${failed.length} seção(ões) indisponível(is).`:'Dados sincronizados agora.');setLoading(false)},[api,config.key]);
 const save=(e:FormEvent)=>{e.preventDefault();localStorage.setItem('finflow-config',JSON.stringify(config));setShowConfig(false);setTimeout(sync,0)};
 const generate=async()=>{setLoading(true);try{setPlan(await api<Plan>('/api/v1/plans',{method:'POST'}));setMsg('Novo plano financeiro gerado.')}catch(e){setMsg((e as Error).message)}finally{setLoading(false)}};
 const review=async(id:string,d:'approve'|'reject')=>{try{const u=await api<Action>(`/api/v1/plans/actions/${id}/${d}`,{method:'PATCH'});setPlan(p=>p?{...p,actions:p.actions.map(a=>a.id===id?u:a)}:p)}catch(e){setMsg((e as Error).message)}};
 const paid=async(kind:'obligations'|'debts',id:string)=>{try{await api(`/api/v1/${kind}/${id}/paid`,{method:'PATCH'});sync()}catch(e){setMsg((e as Error).message)}};
 const total=useMemo(()=>accounts.reduce((s,a)=>s+Number(a.availableBalance.amount),0),[accounts]);const reserve=Math.min(100,plan?.emergencyReserveTarget?.amount?Number(plan.emergencyReserveBalance.amount)/Number(plan.emergencyReserveTarget.amount)*100:0);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><i className="bi bi-graph-up-arrow"/></span><span>finflow</span></div><nav><a className="nav-link active" href="/"><i className="bi bi-grid-1x2-fill"/>Visão geral</a><a className="nav-link" href="/contas"><i className="bi bi-wallet2"/>Contas</a><a className="nav-link" href="#transactions"><i className="bi bi-arrow-left-right"/>Transações</a><a className="nav-link" href="#goals"><i className="bi bi-bullseye"/>Metas</a><a className="nav-link" href="#plan"><i className="bi bi-stars"/>Plano</a></nav><div className="sidebar-bottom"><button className="nav-link btn-reset" onClick={()=>setShowConfig(true)}><i className="bi bi-sliders"/>Conexão API</button><div className="secure-note"><i className="bi bi-shield-check"/><span>Seus dados ficam entre você e sua API.</span></div></div></aside>
 <main className="main-content"><header className="topbar"><div className="mobile-brand">finflow</div><div className="connection"><span className={`status-dot ${config.key?'online':''}`}/>{config.key?'API configurada':'API desconectada'}</div><button className="icon-btn" onClick={()=>setShowConfig(true)}><i className="bi bi-gear"/></button><div className="avatar">GF</div></header><div className="content" id="overview"><section className="hero-row"><div><p className="eyebrow">PAINEL FINANCEIRO</p><h1>Olá! Vamos cuidar do seu dinheiro.</h1><p className="subtitle">Uma visão clara do que importa hoje, sem ruído.</p></div><button className="btn btn-dark rounded-pill px-4" onClick={sync} disabled={loading}><i className={`bi ${loading?'bi-arrow-repeat spin':'bi-arrow-clockwise'} me-2`}/>Sincronizar</button></section><div className="sync-message">{msg}</div>
 <section className="summary-card"><div className="balance-block"><span className="metric-label">Patrimônio disponível</span><strong>{money({amount:plan?.totalConsolidatedBalance?.amount??total,currency:'BRL'})}</strong><span className="metric-caption">em {accounts.length} conta(s)</span></div><div className="divider"/><Metric label="Saldo livre real" value={money(plan?.freeRealBalance)} caption="após compromissos" positive/><Metric label="Limite diário" value={money(plan?.dailySpendingLimit)} caption={`até ${date(plan?.nextIncomeDate)}`}/><Metric label="Comprometido" value={money(plan?.committedObligations)} caption="obrigações futuras"/></section>
 <div className="dashboard-grid"><section className="panel" id="plan"><div className="panel-head"><div><span className="section-kicker">PRÓXIMA MELHOR AÇÃO</span><h2>Seu plano para hoje</h2></div><button className="btn-link-action" onClick={generate}>Gerar novo plano <i className="bi bi-arrow-right"/></button></div>{plan?.actions?.length?<div>{plan.actions.slice(0,3).map((a,i)=><article className="action-item" key={a.id}><span className="action-number">{String(i+1).padStart(2,'0')}</span><div className="action-copy"><div className="d-flex gap-2 align-items-center"><h3>{pretty(a.type)}</h3><span className={`pill ${a.status.toLowerCase()}`}>{pretty(a.status)}</span></div><p>{a.rationale}</p><strong>{money(a.amount)}</strong></div>{a.status==='PROPOSED'&&<div className="action-buttons"><button onClick={()=>review(a.id,'approve')}><i className="bi bi-check-lg"/></button><button onClick={()=>review(a.id,'reject')}><i className="bi bi-x-lg"/></button></div>}</article>)}</div>:<Empty icon="bi-stars" text="Gere seu primeiro plano para receber recomendações."/>}{!!plan?.warnings?.length&&<div className="warning-box"><i className="bi bi-exclamation-circle"/>{plan.warnings[0]}</div>}</section>
 <section className="panel reserve-panel"><span className="section-kicker">RESERVA DE EMERGÊNCIA</span><div className="reserve-ring" style={{'--progress':`${reserve*3.6}deg`} as React.CSSProperties}><div><strong>{Math.round(reserve)}%</strong><span>concluído</span></div></div><h2>{money(plan?.emergencyReserveBalance)}</h2><p>de {money(plan?.emergencyReserveTarget)}</p><div className="progress"><div className="progress-bar" style={{width:`${reserve}%`}}/></div><small>Construindo segurança, um passo de cada vez.</small></section></div>
 <div className="dashboard-grid lower-grid"><ListPanel id="accounts" kicker="SUAS CONTAS" title="Onde está seu dinheiro" count={accounts.length}>{accounts.length?accounts.map(a=><div className="account-row" key={a.id}><span className="account-icon"><i className="bi bi-bank"/></span><div><strong>{a.name}</strong><small>{a.institution} · {pretty(a.purpose)}</small></div><b>{money(a.availableBalance)}</b></div>):<Empty icon="bi-wallet2" text="Nenhuma conta cadastrada."/>}</ListPanel><ListPanel id="goals" kicker="METAS" title="Planos em movimento" count={goals.length}>{goals.length?goals.slice(0,3).map(g=>{const p=Math.min(100,Number(g.currentAmount.amount)/Number(g.targetAmount.amount)*100);return <div className="goal-row" key={g.id}><div className="d-flex justify-content-between"><strong>{g.name}</strong><span>{Math.round(p)}%</span></div><div className="progress"><div className="progress-bar" style={{width:`${p}%`}}/></div><small>{money(g.currentAmount)} de {money(g.targetAmount)}</small></div>}):<Empty icon="bi-bullseye" text="Nenhuma meta cadastrada."/>}</ListPanel></div>
 <section className="panel wide-panel" id="transactions"><PanelHead kicker="MOVIMENTAÇÕES DO MÊS" title="Transações recentes" count={transactions.length}/>{transactions.length?<div className="table-responsive"><table className="table align-middle"><thead><tr><th>Descrição</th><th>Categoria</th><th>Data</th><th className="text-end">Valor</th></tr></thead><tbody>{transactions.slice(0,8).map(t=><tr key={t.id}><td><strong>{t.description}</strong><small>{t.merchant}</small></td><td><span className="category">{pretty(t.category)}</span></td><td>{date(t.occurredAt)}</td><td className={`text-end transaction-value ${t.type==='CREDIT'?'positive':''}`}>{t.type==='DEBIT'?'−':'+'}{money(t.amount)}</td></tr>)}</tbody></table></div>:<Empty icon="bi-receipt" text="Sem transações neste mês."/>}</section>
 <section className="panel wide-panel"><PanelHead kicker="COMPROMISSOS" title="Obrigações e dívidas"/><div className="commitment-grid"><div><h3>Próximos pagamentos</h3>{obligations.filter(o=>o.status==='PENDING').slice(0,4).map(o=><Commitment key={o.id} name={o.name} detail={`Vence ${date(o.dueDate)}`} value={money(o.amount)} action="Marcar pago" onClick={()=>paid('obligations',o.id)}/>)}</div><div><h3>Dívidas ativas</h3>{debts.filter(d=>d.status==='ACTIVE').slice(0,4).map(d=><Commitment key={d.id} name={d.name} detail={`${(Number(d.annualEffectiveRate)*100).toFixed(1)}% a.a.`} value={money(d.outstandingAmount)} action="Quitar" onClick={()=>paid('debts',d.id)}/>)}</div></div></section></div></main>
 {showConfig&&<div className="modal-backdrop-custom" onMouseDown={()=>setShowConfig(false)}><div className="config-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowConfig(false)}><i className="bi bi-x-lg"/></button><span className="brand-mark"><i className="bi bi-plug"/></span><h2>Conectar ao FinFlow</h2><p>Informe o endereço e a chave configurados no backend. A chave fica salva somente neste navegador.</p><form onSubmit={save}><label>URL da API<input className="form-control" type="url" required value={config.url} onChange={e=>setConfig({...config,url:e.target.value})}/></label><label>Chave da API<input className="form-control" type="password" required value={config.key} onChange={e=>setConfig({...config,key:e.target.value})} placeholder="X-API-Key"/></label><button className="btn btn-dark w-100">Salvar e sincronizar</button></form></div></div>}</div>}
function Metric(p:{label:string;value:string;caption:string;positive?:boolean}){return <div className="metric"><span className="metric-label">{p.label}</span><strong className={p.positive?'positive':''}>{p.value}</strong><span className="metric-caption">{p.caption}</span></div>}
function Empty({icon,text}:{icon:string;text:string}){return <div className="empty-state"><i className={`bi ${icon}`}/><span>{text}</span></div>}
function PanelHead({kicker,title,count}:{kicker:string;title:string;count?:number}){return <div className="panel-head"><div><span className="section-kicker">{kicker}</span><h2>{title}</h2></div>{count!==undefined&&<span className="count">{count}</span>}</div>}
function ListPanel({id,kicker,title,count,children}:{id:string;kicker:string;title:string;count:number;children:React.ReactNode}){return <section className="panel" id={id}><PanelHead kicker={kicker} title={title} count={count}/>{children}</section>}
function Commitment({name,detail,value,action,onClick}:{name:string;detail:string;value:string;action:string;onClick:()=>void}){return <div className="commitment"><div><strong>{name}</strong><small>{detail}</small></div><b>{value}</b><button onClick={onClick}>{action}</button></div>}
